import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/HeaderSection";
import Hero from "../components/Hero";
import AboutSection from "@/components/AboutSection";
import PortfolioShowcase from "@/components/PortfolioShowcaseSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Roots Digital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-dark-bg`} suppressHydrationWarning>
        <Header />
        <Hero />
        <AboutSection />
        <PortfolioShowcase />
        <main>{children}</main>
      </body>
    </html>
  );
}
